# Generated by Django 3.2.5 on 2021-08-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
