# Generated by Django 3.2.5 on 2021-08-31 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boards', '0003_upvote_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='upvote',
            name='author',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='accounts.user'),
            preserve_default=False,
        ),
    ]
